sam/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import capellania_sam, usuarios_sam,admisiones_sam, tinymce, secretaria_sam,uniformes_sam,biblioteca_sam, canales_sam, socioeco_sam

from general_sam import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^informes/', include("capellania_sam.urls")),
    url(r'^user/', include("usuarios_sam.urls", namespace="usuarios_sam")),
    url(r'^canales/', include("canales_sam.urls")), 
    url(r'^admisiones/', include("admisiones_sam.urls")),
    url(r'^comunicaciones/', include("comunicaciones_sam.urls")),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^secretaria/', include('secretaria_sam.urls')),
    url(r'^uniformes/', include('uniformes_sam.urls')),
    url(r'^biblioteca/', include('biblioteca_sam.urls')),
    url(r'^personal/', include('personal_sam.urls')),
    url(r'^facturas/', include('facturacion_sam.urls')),
    url(r'^socioeconomico/', include('socioeco_sam.urls')),    
    #url(r'^', views.Mantenimiento, name='mantenimiento,'),
    #url(r'^', views.NoUrl, name='nourl,'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios_sam/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from usuarios_sam import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^login/$',views.login_view, name='login'),
    url(r'^consent/$',views.login_view_app, name='login_view_app'),
    url(r'^logout/$',views.logout_view, name='salida'),
    url(r'^(?P<usuario_id>\d+)/$',views.profile_view, name = "perfil"),
	url(r'^gettoken/$', views.gettoken, name='gettoken'),
	url(r'^gettokenapp/$', views.gettokenapp, name='gettokenapp'),
]
urlpatterns += staticfiles_urlpatterns()

usuarios_sam/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import os

from django.db import models

from PIL import Image
import StringIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django_countries.fields import CountryField
from django.utils import timezone
from django.utils.http import urlquote
from django.core.validators import RegexValidator
from django.core.validators import MaxValueValidator
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class CustomUserManager(BaseUserManager):

    def _create_user(self, first_name, father_last_name, mother_last_name, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        #photo_file = os.path.join("static/user/profile_photo", "default.jpg")
        photo_file = os.path.join("static/user/", "default.jpg")
        user = self.model(email=email, first_name = first_name, father_last_name = father_last_name, mother_last_name = mother_last_name, 
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, user_photo = photo_file, **extra_fields)
        user.set_password(password)

        user.save(using=self._db)
        return user

    def create_user(self, first_name, father_last_name, mother_last_name, email, password=None, **extra_fields):
        return self._create_user(first_name, father_last_name, mother_last_name, email, None ,False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user("", "", "", email, password, True, True,
                                 **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    A fully featured User model with admin-compliant permissions that uses
    a full-length email field as the username.

    Email and password are required. Other fields are optional.
    """
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    identity_regex=RegexValidator(regex=r'^[a-zA-Z0-9_]+$', message= u"Ingrese solo numeros y letras." )
    identity = models.CharField(max_length = 20, validators=[identity_regex], verbose_name = u"Número de Identificación",null = True,blank=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    father_last_name = models.CharField(_('father last name'), max_length=30, blank=False)
    mother_last_name = models.CharField(_('mother last name'), max_length=30, blank=False)
    preferred_name = models.CharField(_('preferred name'), max_length = 30, blank = True)
    birthdate = models.DateField(_('birth date'), null=True, blank = True)
    female ='F'
    male='M'
    gender_choices=(
        (female, 'Femenino'),
        (male, 'Masculino'),
        )
    gender = models.CharField(max_length = 1,choices=gender_choices,default=female,)
    phone_regex=RegexValidator(regex=r'^0+\d{8}$', message= u"Ingrese su teléfono en el formato 022345678." )
    phone = models.CharField(max_length = 9, blank = True, validators=[phone_regex], verbose_name = u"Teléfono del Domicilio")
    cell_regex = RegexValidator(regex=r'^0+\d{9}$', message= u"Ingrese su celular en el formato 0990909090.")
    cell = models.CharField(max_length = 10, blank = True, validators = [cell_regex] , verbose_name = u"Teléfono Celular")
    address = models.CharField(max_length =80, blank = True)
    birth_country = CountryField()
    country_home = CountryField()
    user_photo = models.ImageField(upload_to = "static/user/profile_photo/", default = "static/user/default.jpg")
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        #full_name = ""
        if self.mother_last_name == "":
            full_name = "{0} {1}".format(self.first_name, self.father_last_name)
        else:
            full_name = "{0} {1} {2}".format(self.first_name, self.father_last_name, self.mother_last_name)
        return full_name

    def get_legal_name(self):
        if self.mother_last_name == "":
            legal_name = "{0} {1}".format(self.father_last_name, self.first_name)
        else:
            legal_name = "{0} {1} {2}".format(self.father_last_name, self.mother_last_name, self.first_name)
        return legal_name

    def get_short_name(self):
        "Returns the short name for the user."
        if self.preferred_name == "":
            return self.first_name
        else:
            return self.preferred_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])
"""
    def save(self, *args, **kwargs):
        if self.user_photo:
            image = Image.open(StringIO.StringIO(self.user_photo.read()))
            w, h = image.size
            if w > h:
                image = image.crop((w/2 - h/2 , 0, w/2 + h/2, h))
            else:
                image = image.crop((0, h/2 - w/2, w, h/2 + w/2))

            image = image.resize((600,600), Image.ANTIALIAS)
            output = StringIO.StringIO()
            image.save(output, format='JPEG', quality=75)
            output.seek(0)
            self.user_photo= InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.get_full_name(), 'image/jpeg', output.len, None)
            self.user_photo = os.path.join("static/user/", "default.jpg")
        else:
            self.user_photo = os.path.join("static/user/", "default.jpg")
        super(CustomUser, self).save(*args, **kwargs)
"""        

class LoginRegister(models.Model):
    user = models.ForeignKey("CustomUser")
    login_date = models.DateField(auto_now_add = True)


class Student(models.Model):
    user = models.OneToOneField('CustomUser')
    joined = models.DateTimeField(_('date joined'), default=timezone.now)
    through = models.CharField(_('joined thourgh'), max_length = 50, blank = True)

    def __unicode__(self):
        return self.user.get_legal_name()

    def get_name(self):
        return self.user.get_legal_name()


class Relative(models.Model):
    user = models.OneToOneField('CustomUser')
    joined = models.DateTimeField(_('date joined'), default=timezone.now)
    through = models.CharField(_('joined thourgh'), max_length = 50, blank = True)

    def __unicode__(self):
        return self.user.get_legal_name()

class Relative_Details(models.Model):
    relative = models.OneToOneField("Relative")
    alive = models.BooleanField(default = True)
    instruction=models.CharField(max_length =50,blank=True,null=True)
    profession=models.CharField(max_length =50,blank=True,null=True)
    address_work=models.CharField(max_length =80,blank=True,null=True)
    office_regex=RegexValidator(regex=r'^0+\d{8}$', message= u"Ingrese su teléfono en el formato 022345678." )
    office = models.CharField(max_length = 9, validators=[office_regex], verbose_name = _('office phone'))


    def __unicode__(self):
        return self.relative.user.get_legal_name()




class Student_Relative(models.Model):
    student = models.ForeignKey("Student")
    relative = models.ForeignKey("Relative")
    relationship = models.CharField(max_length = 20)
    legal_representative = models.BooleanField(default = False)
    live_together = models.BooleanField(default = False)
    withdraw = models.BooleanField(default = False)
    notifications = models.BooleanField(default = False)

    class Meta:
        unique_together = (('student', 'relative'))

    def __unicode__(self):
        return u"{0}-{1}:{2}".format(self.student.user.get_legal_name(), self.relative.user.get_legal_name(), self.relationship)

    
class Students(models.Model):
    id_students = models.ForeignKey('CustomUser', related_name = "Estudiante", unique = True)
    id_tutor=models.ForeignKey('usuarios_sam.CustomUser', related_name = "Tutor")
    id_father=models.ForeignKey('usuarios_sam.CustomUser', related_name = "Padre",blank=True,null=True)
    id_mother=models.ForeignKey('usuarios_sam.CustomUser', related_name = "Madre",blank=True,null=True)
    applied_grade = models.CharField(max_length =50)
    medical_information = models.CharField(max_length =80)
    id_applications=models.ForeignKey('admisiones_sam.Applications',blank=True,null=True)
    

    def __unicode__(self):
        return self.id_students.get_full_name()

    def get_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        #full_name = ""
        name = "{0} {1} {2}".format(self.id_students.father_last_name, self.id_students.mother_last_name, self.id_students.first_name)
        return name
    
    
class People(models.Model):

usuarios_sam/views.py
from django.shortcuts import render, redirect

from django.core.files.storage import FileSystemStorage

import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from usuarios_sam.models import CustomUser as User




from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from usuarios_sam.authhelper import get_consent_url , get_signin_url, get_token_from_code, get_access_token, get_token_from_shared_secret

import time
from usuarios_sam.outlookservice import get_me, get_my_messages, get_my_photo, get_users

from PIL import Image
from io import BytesIO

import os

def login_view_app(request):
    redirect_uri = request.build_absolute_uri(reverse('usuarios_sam:gettokenapp'))
    sign_in_url = get_consent_url(redirect_uri)


    return redirect(sign_in_url)


def login_view(request):
    request.session["redirect"] = request.GET.get("next","")
    redirect_uri = request.build_absolute_uri(reverse('usuarios_sam:gettoken'))
    sign_in_url = get_signin_url(redirect_uri)

    return redirect(sign_in_url)

    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect (index)
        else:
            return render (request, "gentelella/production/login.html", {})
    else:
        return render (request, "gentelella/production/login.html", {})


def gettoken(request):
    auth_code = request.GET['code']
    redirect_uri = request.build_absolute_uri(reverse('usuarios_sam:gettoken'))
    token = get_token_from_code(auth_code, redirect_uri)
    access_token = token['access_token']
    refresh_token = token['refresh_token']
    expires_in = token['expires_in']

    user = get_me(access_token)

    first_name = user['givenName']
    name = user['displayName']
    last_name = name[len(first_name)+1:len(name)]

    # expires_in is in seconds
    # Get current timestamp (seconds since Unix Epoch) and
    # add expires_in to get expiration time
    # Subtract 5 minutes to allow for clock differences
    expiration = int(time.time()) + expires_in - 300

    # Save the token in the session
    request.session['access_token'] = access_token
    request.session['refresh_token'] = refresh_token
    request.session['token_expires'] = expiration
    request.session['user_email'] = user['mail']

    user_email = str(user["mail"])


    user = authenticate(email=user_email, token =access_token, first_name = first_name, last_name = last_name, name = name, request = request)
    if user is not None:
        login(request, user)
        return redirect(request.session["redirect"])
    else:
        return redirect(request.session["redirect"])



def gettokenapp(request):
    #redirect_uri = request.build_absolute_uri(reverse('usuarios_sam:gettokenapp'))
    token = get_token_from_shared_secret()
    access_token = token['access_token']
    #refresh_token = token['refresh_token']
    expires_in = token['expires_in']

    #user = get_me(access_token)

    #first_name = user['givenName']
    #name = user['displayName']
    #last_name = name[len(name)-len(first_name):len(name)]

    # expires_in is in seconds
    # Get current timestamp (seconds since Unix Epoch) and
    # add expires_in to get expiration time
    # Subtract 5 minutes to allow for clock differences
    expiration = int(time.time()) + expires_in - 300

    # Save the token in the session
    request.session['access_token'] = access_token
    #request.session['refresh_token'] = refresh_token
    request.session['token_expires'] = expiration

    #user_email = str(user["mail"])


    user = authenticate(email="rodrigo@montebelloacademy.org", token =access_token, first_name = None, last_name = None, name = None, request = request)
    if user is not None:
        login(request, user)
        return redirect("https://canaldocente.montebelloacademy.org/canales/")
    else:
        return redirect("https://canaldocente.montebelloacademy.org/canales/")
    #return HttpResponseRedirect(reverse('api:mail'))

     
def logout_view(request):
    logout(request)
    return redirect("https://login.windows.net/common/oauth2/logout?post_logout_redirect_uri={0}".format("https://192.99.20.125{0}".format(reverse('usuarios_sam:login'))))
    #return HttpResponseRedirect(reverse('usuarios_sam:login'))


@login_required(login_url="/user/login/")    
def index(request):
    if request.method == "POST" and request.FILES['photo']:
        photo = request.FILES["photo"]
        fs = FileSystemStorage()
        new_photo = fs.save("static/user/profile_photo/"+photo.name, photo)
        user = User.objects.get(pk = request.user.pk)
        user.user_photo = new_photo
        user.save()
        request.user = user
        return render(request, "custom/profile.html", {})
    else:
        return render(request, "custom/profile.html", {})


@login_required()    
def profile_view(request, usuario_id):
    user = User.objects.get(pk = usuario_id)
    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        new_password_2 = request.POST.get("new_password_2")
        if new_password != new_password_2:
            return render (request, "gentelella/production/change_password.html", {"error":"Las contrasenas no son iguales"})
        else:
            user.set_password(new_password)
            user.save()
            login(request, user)
            return redirect("/user")
    else:
        return render (request, "usuarios_sam/perfil_usuario.html", {"usuario":user})
    
    
# Create your views here.

usuarios_sam/templates/usuarios_sam/perfil_usuario.html
{% extends "gentelella/production/plain_page.html" %}
{% load staticfiles %}
{% load extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
 {% block cabecera %}  
    
    <link rel="stylesheet" href="{% static 'contact-form/css/datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'contact-form/css/datepicker3.min.css' %}">
    <link rel="stylesheet" href="{% static 'contact-form/css/sb-admin-2.css' %}">
    <link rel="stylesheet" href="{% static 'contact-form/css/style.css' %}" type="text/css">

  {% endblock%}  

 
   </head> 

 {%block contenido %}


    <div class="container_fluid">
        <div class="container page-header">
            <div class="col-md-4">
                <img src="{% static 'logo.png' %}" width="120" height="120">
            </div>
            <div class="col-md-8" "col-sm-8" "col-xs-8" align="right">
                <h1>Montebello Academy</h1>
                <h3>{{usuario.get_full_name | title}}</h3>
            </div>
        </div>

        <div class="container page-body">
            <div class="row">
                <div class="col-md-2">
                    <img src="{{usuario.user_photo.url}}" class="img-responsive" alt="..." class="img-rounded">
                </div>

                <div class="col-md-10">
                    {% if usuario.student %}
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="panel-title">Información de representantes</div>
                        </div>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nombres</th>
                                    <th>Relación</th>
                                    <th>Celular</th>
                                    <th>Email</th>
                                </tr>
                            </thead>                        
                            <tbody>
                                {% for representante in usuario.student.student_relative_set.all %}

                                <tr>
                                    <td><a href="/user/{{representante.relative.user.pk}}">{{representante.relative.user.get_full_name|title}}</a></td>
                                    <td>{{representante.relationship}}</td>
                                    <td><a href="tel:{{representante.relative.user.cell}}">{{representante.relative.user.cell}}</a></td>
                                    <td><a href="mailto:{{representante.relative.user.email}}">{{representante.relative.user.email}}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                       
                    </div>
                    {% endif %}

                    {% if usuario.relative %}
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="panel-title">Información de Estudiantes</div>
                        </div>                    
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nombres</th>
                                    <th>Relación</th>
                                    <th>Nivel</th>
                                    <th>Email</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for estudiante in usuario.relative.student_relative_set.all %}

                                <tr>
                                    <td><a href="/user/{{estudiante.student.user.pk}}">{{estudiante.student.user.get_full_name|title}}</a></td>
                                    <td>{{estudiante.relationship}}</td>
                                    <td>{% for registro in estudiante.student.matricula_set.all %}
                                        {% ifequal schoolyear registro.clase.periodo_lectivo %}
                                        {{estudiante.student.matricula_set.last.clase}}
                                        {% else %}No registrado
                                        {%endifequal%}
                                        {% endfor %}
                                    </td>
                                    <td>{{estudiante.student.user.email}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% endif %}                
                    <div class="row">
                        <div class="col-md-12">
                            <div class="page-header">
                                <h3>Información Personal</h3>
                            </div>


                            <form class="form-horizontal">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">No. Identidad</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static input-sm">{{usuario.identity}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Apellido Paterno</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.father_last_name|title}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Apellido Materno</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.mother_last_name|title}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Nombres</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.first_name|title}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Nombre Preferido</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.preferred_name|title}}</p>
                                        </div>
                                    </div>                                                                                                                                                
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Fecha de Nacimiento</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.birthdate}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Lugar de Nacimiento</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.birth_country.name}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Correo electrónico</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.email}}</p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Teléfono celular</label>
                                        <div class="col-sm-8">
                                            <p class="form-control-static">{{usuario.cell}}</p>
                                        </div>
                                    </div>                                                                                                                                      
                            
                                </div>
                            </form>
                        </div>         

                    </div>

                </div>
            </div>
            <!--
            <div class="row">
                <div class="col-md-8">
                    <h3>Domicilio</h3>
                </div>
                <div class="col-md-4">
                    <h3>Transporte</h3>
                </div>

            </div>

-->

        </div>



    </div>







{% endblock %}



 {% block scripts %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'contact-form/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'contact-form/js/modernizr.js' %}" type="text/javascript"></script>
    <script src="{% static 'contact-form/js/jquery.min.js' %}"></script>
    <script src="{% static 'contact-form/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'contact-form/js/bootstrapvalidator.min.js'%}"></script>
    <script src="{% static 'contact-form/js/bootstrap-datepicker.min.js'%}"></script>
    <script src="{% static 'contact-form/js/index.js'%}"></script>





    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="http://jqueryui.com/resources/demos/style.css">





    <script src="{% static 'contact-form/js/index.js'%}"></script>
    

  {% endblock %}

   
    
</body>
</html>